"""Transactional outbox for every domain, including SQL and background writers.

Revision ID: 0050
Revises: 0049
"""
from alembic import op

revision = "0050"
down_revision = "0049"
branch_labels = None
depends_on = None

# table, event family, audience, scope source (parent for child records).
# The trigger contains no PHI and executes inside the application's transaction.
SOURCES = [
    ("pacientes", "patient", "staff", "r"),
    ("citas", "appointment", "staff", "r"),
    ("citas_telefonear", "appointment", "staff", "SELECT to_jsonb(p) FROM citas p WHERE p.id = (r->>'cita_original_id')::uuid"),
    ("historial_clinico", "treatment", "clinical", "r"),
    ("notas_dentales", "note", "clinical", "r"),
    ("sesion_clinica_items", "treatment", "clinical", "r"),
    ("presupuestos", "budget", "staff", "r"),
    ("presupuesto_lineas", "budget", "staff", "SELECT to_jsonb(p) FROM presupuestos p WHERE p.id = (r->>'presupuesto_id')::uuid"),
    ("trabajo_pendiente", "budget", "staff", "r"),
    ("facturas", "invoice", "billing", "r"),
    ("factura_lineas", "invoice", "billing", "SELECT to_jsonb(p) FROM facturas p WHERE p.id = (r->>'factura_id')::uuid"),
    ("cobros", "payment", "billing", "SELECT COALESCE(to_jsonb(p), r) || jsonb_build_object('paciente_id', COALESCE(r->>'paciente_id', p.paciente_id::text)) FROM (SELECT 1) x LEFT JOIN facturas p ON p.id = (r->>'factura_id')::uuid"),
    ("pagos_anticipados_paciente", "payment", "billing", "r"),
    ("cargos_paciente", "balance", "billing", "r"),
    ("aplicaciones_pago", "balance", "billing", "SELECT to_jsonb(p) FROM cargos_paciente p WHERE p.id = (r->>'cargo_id')::uuid"),
    ("documentos_paciente", "document", "document", "r"),
    ("consentimientos", "document", "clinical", "r"),
    ("recetas_clinicas", "prescription", "clinical", "r"),
    ("trabajos_laboratorio", "laboratory", "staff", "r"),
    ("odontogramas", "odontogram", "clinical", "r"),
    ("odontograma_piezas", "odontogram", "clinical", "SELECT to_jsonb(p) FROM odontogramas p WHERE p.id = (r->>'odontograma_id')::uuid"),
    ("odontograma_superficies", "odontogram", "clinical", "SELECT to_jsonb(p) FROM odontogramas p JOIN odontograma_piezas i ON i.odontograma_id = p.id WHERE i.id = (r->>'pieza_id')::uuid"),
    ("productos", "inventory", "admin", "r"),
    ("proveedores", "inventory", "admin", "r"),
    ("pedidos_proveedor", "inventory", "admin", "r"),
    ("pedido_lineas", "inventory", "admin", "SELECT to_jsonb(p) FROM pedidos_proveedor p WHERE p.id = (r->>'pedido_id')::uuid"),
    ("movimientos_inventario", "inventory", "admin", "SELECT to_jsonb(p) FROM productos p WHERE p.id = (r->>'producto_id')::uuid"),
    ("doctor_notifications", "notification", "doctor", "r"),
    ("whatsapp_comunicaciones", "communication", "staff", "r"),
]


def upgrade():
    op.execute("""
        CREATE SEQUENCE realtime_delivery_seq;
        CREATE TABLE realtime_events (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            sequence bigint UNIQUE,
            event_type varchar(80) NOT NULL, entity_type varchar(80) NOT NULL,
            entity_id uuid NOT NULL, clinica_id uuid, paciente_id uuid, doctor_id uuid,
            audience varchar(30) NOT NULL, created_at timestamptz NOT NULL DEFAULT now()
        );
        CREATE INDEX ix_realtime_events_pending ON realtime_events(id) WHERE sequence IS NULL;
    """)
    for table, family, audience, source in SOURCES:
        scope = "s := r;" if source == "r" else f"s := ({source});"
        op.execute(f"""
        CREATE FUNCTION realtime_{table}() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE r jsonb; s jsonb; patient uuid; clinic uuid; professional uuid;
                kind text; visibility text; record jsonb;
        BEGIN
            IF TG_OP = 'UPDATE' AND NEW IS NOT DISTINCT FROM OLD THEN RETURN NEW; END IF;
            -- Emit both tenant scopes if ownership is reassigned; never send the new
            -- clinic's contents to the previous clinic. Clients only invalidate reads.
            FOR record IN SELECT value FROM jsonb_array_elements(
                CASE WHEN TG_OP = 'DELETE' THEN jsonb_build_array(to_jsonb(OLD))
                     WHEN TG_OP = 'UPDATE' AND to_jsonb(OLD)->'clinica_id' IS DISTINCT FROM to_jsonb(NEW)->'clinica_id'
                     THEN jsonb_build_array(to_jsonb(OLD), to_jsonb(NEW))
                     ELSE jsonb_build_array(to_jsonb(NEW)) END)
            LOOP
                r := record;
                {scope}
                -- A missing parent is not a legacy row with a null clinic.
                -- Its own event invalidates the parent; fail closed for children.
                IF s IS NULL THEN CONTINUE; END IF;
                patient := COALESCE(s->>'paciente_id', s->>'patient_id')::uuid;
                IF TG_TABLE_NAME = 'pacientes' THEN patient := (r->>'id')::uuid; END IF;
                clinic := (s->>'clinica_id')::uuid;
                IF patient IS NOT NULL AND TG_TABLE_NAME <> 'pacientes' THEN
                    SELECT p.clinica_id INTO clinic FROM pacientes p WHERE p.id = patient;
                    IF NOT FOUND THEN CONTINUE; END IF;
                END IF;
                professional := COALESCE(s->>'recipient_doctor_id', s->>'doctor_id')::uuid;
                kind := '{family}.' || CASE TG_OP WHEN 'INSERT' THEN 'created' WHEN 'DELETE' THEN 'deleted' ELSE 'updated' END;
                visibility := '{audience}';
                IF TG_TABLE_NAME = 'documentos_paciente' THEN
                    visibility := CASE WHEN r->>'categoria' = 'factura' THEN 'billing'
                        WHEN r->>'categoria' IN ('presupuesto', 'circular') THEN 'staff' ELSE 'clinical' END;
                END IF;
                INSERT INTO realtime_events(event_type, entity_type, entity_id, clinica_id, paciente_id, doctor_id, audience)
                VALUES(kind, TG_TABLE_NAME, (r->>'id')::uuid, clinic, patient, professional, visibility);
            END LOOP;
            PERFORM pg_notify('dentcore_changes', '');
            RETURN COALESCE(NEW, OLD);
        END $$;
        CREATE TRIGGER realtime_change AFTER INSERT OR UPDATE OR DELETE ON {table}
        FOR EACH ROW EXECUTE FUNCTION realtime_{table}();
        """)


def downgrade():
    for table, *_ in reversed(SOURCES):
        op.execute(f"DROP TRIGGER realtime_change ON {table}; DROP FUNCTION realtime_{table}();")
    op.execute("DROP TABLE realtime_events; DROP SEQUENCE realtime_delivery_seq;")
